name: Skor Çekme İşlemi

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  # 1. AŞAMA: HER ENSTRÜMAN İÇİN VERİLERİ PARALEL ÇEK VE ARŞİVLE
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instrument:
          - 'Solo_Guitar'
          - 'Solo_Drums'
          - 'Solo_Bass'
          - 'Solo_Vocals'
          - 'Solo_PeripheralGuitar'
          - 'Solo_PeripheralBass'
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      # Her iş için temiz bir çıktı klasörü oluşturuyoruz
      - name: Create output directory
        run: mkdir ./output

      - name: Run Scraper for ${{ matrix.instrument }}
        env:
          EPIC_REFRESH_TOKEN: ${{ secrets.EPIC_REFRESH_TOKEN }}
          EPIC_BASIC_AUTH: ${{ secrets.EPIC_BASIC_AUTH }}
        # Script'e çıktıları ./output klasörüne yazmasını söylüyoruz
        run: python actions.py ${{ matrix.instrument }} ./output

      # Sadece oluşturulan dosyaları içeren temiz klasörü artifact olarak yüklüyoruz
      - name: Upload leaderboards artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaderboards-${{ matrix.instrument }}
          path: ./output/leaderboards/

  # 2. AŞAMA: TÜM TARAMA BİTTİKTEN SONRA DOSYALARI KAYDET
  commit-files:
    needs: scrape
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Tüm artifact'leri indir ve birleştir. Bu işlem, mevcut leaderboards klasörünün üzerine
      # hem güncel verileri yazar hem de yeni şarkıların klasörlerini ekler.
      - name: Download all leaderboards artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: leaderboards-*
          merge-multiple: true
          path: leaderboards/ # İndirilen dosyaları doğrudan leaderboards klasörüne çıkar

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Data: Update all leaderboards"
          # leaderboards klasöründeki tüm değişiklikleri (yeni/güncel) yakala
          file_pattern: leaderboards
