Name: Fortnite Festival Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  # 1. AŞAMA: HER ENSTRÜMAN İÇİN VERİLERİ ÇEK VE ARŞİVLE
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instrument:
          - 'Solo_Guitar'
          - 'Solo_Drums'
          - 'Solo_Bass'
          - 'Solo_Vocals'
          - 'Solo_PeripheralGuitar'
          - 'Solo_PeripheralBass'
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper for ${{ matrix.instrument }}
        env:
          # EPIC_REFRESH_TOKEN ve YENİ SECRET'ınız artık GitHub Secrets'tan okunacak.
          EPIC_REFRESH_TOKEN: ${{ secrets.EPIC_REFRESH_TOKEN }}
          EPIC_BASIC_AUTH: ${{ secrets.EPIC_BASIC_AUTH }}
        run: python scraper_actions.py ${{ matrix.instrument }}

      # Oluşturulan dosyaları bir sonraki iş için artifact olarak yükle
      - name: Upload leaderboards artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaderboards-${{ matrix.instrument }}
          path: leaderboards/

  # 2. AŞAMA: TÜM TARAMA BİTTİKTEN SONRA DOSYALARI KAYDET
  commit-files:
    # Bu iş, 'scrape' işinin tüm matrisleri başarıyla bittikten sonra başlar
    needs: scrape
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Tüm enstrümanların artifact'larını indir ve birleştir
      - name: Download all leaderboards artifacts
        uses: actions/download-artifact@v4
        with:
          path: leaderboards/
          pattern: leaderboards-*
          merge-multiple: true

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Data: Update all leaderboards"
          file_pattern: "leaderboards/**/*.json"
