name: Skor Çekme İşlemi

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    # Commit yapabilmek için gerekli izin
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        # Token kullanarak checkout yapıyoruz ki push işlemi yapabilelim
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      # BÜTÜN ENSTRÜMANLARI SIRAYLA TARA
      # Her enstrüman için script'i çalıştıracak ve dosyaları doğrudan checkout edilen klasöre yazacak
      - name: Run Scraper for all instruments
        env:
          EPIC_REFRESH_TOKEN: ${{ secrets.EPIC_REFRESH_TOKEN }}
          EPIC_BASIC_AUTH: ${{ secrets.EPIC_BASIC_AUTH }}
        run: |
          python scraper_actions.py Solo_Guitar
          python scraper_actions.py Solo_Drums
          python scraper_actions.py Solo_Bass
          python scraper_actions.py Solo_Vocals
          python scraper_actions.py Solo_PeripheralGuitar
          python scraper_actions.py Solo_PeripheralBass

      # DEĞİŞİKLİKLERİ COMMIT'LE
      # Tüm taramalar bittikten sonra, eğer bir değişiklik varsa (güncelleme veya yeni dosya) commit yap
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Data: Update all leaderboards"
          # Bu, leaderboards klasöründeki her türlü değişikliği yakalar (yeni, güncel, silinmiş)
          file_pattern: leaderboards/
