name: Fortnite Festival Scraper

on:
  workflow_dispatch:

  schedule:
    # Her gün UTC saatiyle 00:00'da (Türkiye saatiyle 03:00) çalışır
    - cron: '0 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instrument:
          - 'Solo_Guitar'
          - 'Solo_Drums'
          - 'Solo_Bass'
          - 'Solo_Vocals'
          - 'Solo_PeripheralGuitar'
          - 'Solo_PeripheralBass'
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper for ${{ matrix.instrument }}
        env:
          API_URL: ${{ secrets.API_URL }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          EPIC_REFRESH_TOKEN: ${{ secrets.EPIC_REFRESH_TOKEN }}
        run: python scraper_actions.py ${{ matrix.instrument }}
