name: Fortnite Festival Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      # --- YENİ EKLENEN SATIR ---
      # Bu satır, matristeki işlerin aynı anda sadece 1 tane çalışmasını sağlar.
      # Bu sayede "non-fast-forward" hatası önlenir.
      max-parallel: 1
      
      matrix:
        instrument:
          - 'Solo_Guitar'
          - 'Solo_Drums'
          - 'Solo_Bass'
          - 'Solo_Vocals'
          - 'Solo_PeripheralGuitar'
          - 'Solo_PeripheralBass'
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper for ${{ matrix.instrument }}
        env:
          EPIC_REFRESH_TOKEN: ${{ secrets.EPIC_REFRESH_TOKEN }}
        run: python scraper_actions.py ${{ matrix.instrument }}

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Data: Update leaderboards for ${{ matrix.instrument }}"
          file_pattern: "leaderboards/**/*.json"
